DROP TABLE IF EXISTS public.completed_games CASCADE;

CREATE TABLE public.completed_games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  word_id INT NOT NULL,
  guess_count SMALLINT NOT NULL,
  result BOOLEAN NOT NULL,
  duration interval NOT NULL,
  game_type_id INT NOT NULL,
  date_completed TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT completed_games_game_type_id_fkey FOREIGN KEY (game_type_id) REFERENCES public.game_types (id),
  CONSTRAINT completed_games_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id),
  CONSTRAINT completed_games_word_id_fkey FOREIGN KEY (word_id) REFERENCES public.words (id)
) TABLESPACE pg_default;