DROP TABLE IF EXISTS public.completed_game_sessions CASCADE;

CREATE TABLE public.completed_game_sessions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed_game_id INT NOT NULL REFERENCES public.completed_games(id) ON DELETE CASCADE,
  game_session_id INT NOT NULL REFERENCES public.game_sessions(id) ON DELETE CASCADE
);