DROP TABLE IF EXISTS public.game_sessions CASCADE;

CREATE TABLE public.game_sessions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_type_id  INT  NOT NULL REFERENCES public.game_types(id)
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS game_sessions_user_type_idx
  ON public.game_sessions(user_id, game_type_id);